version: "3.8"
name: template-backend
services:
  db:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME:-template_postgres}
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-template_db}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  sonarqube:
    container_name: ${SONARQUBE_CONTAINER_NAME:-sonarqube}
    image: sonarqube:25.2.0.102705-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://${SONAR_DB_CONTAINER_NAME:-sonar_db}:5432/${SONAR_DB_NAME:-sonar}
      SONAR_JDBC_USERNAME: ${SONAR_DB_USER:-sonar}
      SONAR_JDBC_PASSWORD: ${SONAR_DB_PASSWORD:-sonar}
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
  sonar_db:
    container_name: ${SONAR_DB_CONTAINER_NAME:-sonar_db}
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SONAR_DB_USER:-sonar}
      POSTGRES_PASSWORD: ${SONAR_DB_PASSWORD:-sonar}
      POSTGRES_DB: ${SONAR_DB_NAME:-sonar}
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data
volumes:
  local_pgdata:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data: