version: "3.8"
name: template-backend
services:
  db:
    image: postgres
    container_name: template_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  
volumes:
  local_pgdata: